### ISSUE TITLE
Написать документацию

### ISSUE THREAD

**Issue by trabem** [black-lamp/yii2-imagable#1]
Нужно написать документацию к этому модулю.
Разделы:
- Конфигурация компонента
- Использование

**Comment by RuslanSaiko** [comment]
Fix in https://github.com/black-lamp/yii2-imagable/commit/33bbb68c67d3a827b1e62006f940b0b92948496f

**Comment by trabem** [comment]
Fix in https://github.com/black-lamp/yii2-imagable/commit/33bbb68c67d3a827b1e62006f940b0b92948496f
